routes/web.php
<?php

use App\Http\Controllers\ActionController;
use App\Http\Controllers\ActivityController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\ContentController;
use App\Http\Controllers\DraftController;
use App\Http\Controllers\EditionController;
use App\Http\Controllers\FAQController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\ProgramController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\TrashController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web rout   es for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::group(['prefix' => 'login'], function () {
    Route::get('/microsoft', [LoginController::class, 'redirectToProvider']);
    Route::get('/microsoft/callback', [LoginController::class, 'handleProviderCallback']);
});


Route::group(['prefix' => 'activity'], function () {
    Route::post('/participate/{id}', [ActionController::class, 'participate'])->name('public.activity.participate');
    Route::post('/retire/{id}', [ActionController::class, 'retire'])->name('public.activity.retire');

    Route::post('/favorite/{id}', [ActionController::class, 'favorite'])->name('public.activity.favorite');
    Route::post('/unfavorite/{id}', [ActionController::class, 'unfavorite'])->name('public.activity.unfavorite');
});


Route::group([
    'middleware' => ['auth:sanctum', 'verified', 'is_due'],
    'prefix' => 'admin/'
], function () {
    Route::get('/dashboard', [PagesController::class, 'adminDashboard'])->name('dashboard');

    Route::group(['prefix' => 'activity'], function () {
        Route::get('/show/{activity}', [ActivityController::class, 'show']);
        Route::get('/list', [ActivityController::class, 'index'])->name('pages.activity.list');

        Route::get('/edit/{id}', [ActivityController::class, 'edit'])->name('pages.activity.edit');
        Route::put('/update/{activity}', [ActivityController::class, 'update'])->name('pages.activity.update');
    });

    Route::get('/participants/{id}', [ProgramController::class, 'listParticipants'])->name('pages.participant.list');
    Route::get('/participants/edit/{id}', [ProgramController::class, 'editParticipants'])->name('pages.participant.edit');
    Route::post('/participants/add', [ProgramController::class, 'addParticipants'])->name('pages.participant.add');
    Route::post('/participants/remove', [ProgramController::class, 'retireParticipant'])->name('pages.participant.retire');
    Route::get('/program', [ProgramController::class, 'listProgram'])->name('pages.program.list');
    Route::get('/favorite', [ProgramController::class, 'listFavorite'])->name('pages.program.favorite');

    Route::group(['prefix' => 'draft'], function () {
        Route::get('/show/{activity}', [DraftController::class, 'show']);
        Route::get('/list', [DraftController::class, 'index'])->name('pages.draft.list');

        Route::get('/edit/{id}', [DraftController::class, 'edit'])->name('pages.draft.edit');
        Route::get('/create', [DraftController::class, 'create'])->name('pages.draft.create');
        Route::post('/store', [DraftController::class, 'store'])->name('pages.draft.store');
        Route::put('/update/{activity}', [DraftController::class, 'update'])->name('pages.draft.update');
    });

    Route::group([
        'middleware' => 'is_admin'
    ], function () {
        Route::group(['prefix' => 'activity'], function () {
            Route::delete('/delete/{activity}', [ActivityController::class, 'destroy'])->name('pages.activity.delete');
        });

        Route::get('auth/register', [LoginController::class, 'viewRegister'])->name('auth.register.view');
        Route::post('auth/register', [LoginController::class, 'register'])->name('auth.register');

        Route::group(['prefix' => 'location'], function () {
            Route::get('/list', [LocationController::class, 'index'])->name('pages.location.list');

            Route::get('/edit/{id}', [LocationController::class, 'edit'])->name('pages.location.edit');
            Route::get('/create', [LocationController::class, 'create'])->name('pages.location.create');

            Route::post('/store', [LocationController::class, 'store'])->name('pages.location.store');
            Route::put('/update/{location}', [LocationController::class, 'update'])->name('pages.location.update');

            Route::delete('/delete/{location}', [LocationController::class, 'destroy'])->name('pages.location.delete');
        });

        Route::group(['prefix' => 'tag'], function () {
            Route::get('/list', [TagController::class, 'index'])->name('pages.tag.list');

            Route::get('/edit/{id}', [TagController::class, 'edit'])->name('pages.tag.edit');
            Route::get('/create', [TagController::class, 'create'])->name('pages.tag.create');

            Route::post('/store', [TagController::class, 'store'])->name('pages.tag.store');
            Route::put('/update/{tag}', [TagController::class, 'update'])->name('pages.tag.update');

            Route::delete('/delete/{tag}', [TagController::class, 'destroy'])->name('pages.tag.delete');
        });

        Route::group(['prefix' => 'faq'], function () {
            Route::get('/list', [FAQController::class, 'index'])->name('pages.faq.list');

            Route::get('/edit/{id}', [FAQController::class, 'edit'])->name('pages.faq.edit');
            Route::get('/create', [FAQController::class, 'create'])->name('pages.faq.create');

            Route::post('/store', [FAQController::class, 'store'])->name('pages.faq.store');
            Route::put('/update/{faq}', [FAQController::class, 'update'])->name('pages.faq.update');

            Route::delete('/delete/{faq}', [FAQController::class, 'destroy'])->name('pages.faq.delete');
        });

        Route::group(['prefix' => 'edition'], function () {
            Route::get('/list', [EditionController::class, 'index'])->name('pages.edition.list');

            Route::get('/edit/{edition}', [EditionController::class, 'edit'])->name('pages.edition.edit');
            Route::put('/update/{edition}', [EditionController::class, 'update'])->name('pages.edition.update');

            Route::delete('/delete/{edition}', [EditionController::class, 'destroy'])->name('pages.edition.delete');
        });

        Route::group(['prefix' => 'trash'], function () {
            Route::get('/list', [TrashController::class, 'index'])->name('pages.trash.list');
            Route::put('/update/{id}', [TrashController::class, 'update'])->name('pages.trash.restore');
            Route::delete('/delete/{id}', [TrashController::class, 'destroy'])->name('pages.trash.delete');
        });

        Route::group(['prefix' => 'user'], function () {
            Route::get('/show/{user}', [UserController::class, 'show']);
            Route::get('/list', [UserController::class, 'index'])->name('pages.user.list');

            Route::get('/edit/{user}', [UserController::class, 'edit'])->name('pages.user.edit');
            Route::get('/create', [UserController::class, 'create'])->name('pages.trash.user');

            Route::post('/store', [UserController::class, 'store'])->name('pages.user.store');
            Route::put('/update/{user}', [UserController::class, 'update'])->name('pages.user.update');

            Route::delete('/delete/{user}', [UserController::class, 'destroy'])->name('pages.user.delete');
        });

        Route::group(['prefix' => 'content'], function () {
            Route::get('/show/{content}', [ContentController::class, 'show']);
            Route::get('/list', [ContentController::class, 'index'])->name('pages.content.list');

            Route::get('/edit/{content}', [ContentController::class, 'edit'])->name('pages.content.edit');
            Route::get('/create', [ContentController::class, 'create'])->name('pages.content.create');

            Route::post('/store', [ContentController::class, 'store'])->name('pages.content.store');
            Route::put('/update/{content}', [ContentController::class, 'update'])->name('pages.content.update');

            Route::delete('/delete/{content}', [ContentController::class, 'destroy'])->name('pages.content.delete');
        });
    });
});

Route::group([
    'middleware' => ['auth:sanctum', 'verified', 'set_language'],
    'prefix' => '{language}/public/'
], function () {
    Route::get('/dashboard', [PagesController::class, 'publicDashboard'])->name('public.dashboard');

    Route::get('/faq', [PagesController::class, 'getFaq'])->name('public.faq');

    Route::group(['prefix' => 'activity'], function () {
        Route::get('/list', [PagesController::class, 'getActivityList'])->name('public.activity.list');
        Route::get('/calender', [PagesController::class, 'getActivityCalender'])->name('public.activity.calender');
    });

    Route::get('/about-think-fest', [PagesController::class, 'getAboutThinkFest'])->name('public.about-think-fest');
    Route::get('/program', [PagesController::class, 'getProgram'])->name('public.program');
    Route::get('/toolkit', [PagesController::class, 'getPressKit'])->name('public.press-kit');
    Route::get('/contact', [PagesController::class, 'getContact'])->name('public.contact');
    Route::get('/privacy-statement', [PagesController::class, 'getPrivacyStatement'])->name('public.privacy-statement');
    Route::get('/cookies', [PagesController::class, 'getCookies'])->name('public.cookies');
    Route::get('/ednext', [PagesController::class, 'getEdNext'])->name('public.ednext');
});

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/arkdown=conceptToActivity.blade.php
@component('mail::message')
# Introduction

The body of your message.

@component('mail::button', ['url' => ''])
Button Text
@endcomponent

Thanks,<br>
{{ config('app.name') }}
@endcomponent

resources/views/conceptToActivity.blade.php
@component('mail::message')
# Introduction

The body of your message.

@component('mail::button', ['url' => ''])
Button Text
@endcomponent

Thanks,<br>
{{ config('app.name') }}
@endcomponent

resources/views/createConceptMail.blade.php
@component('mail::message')
# Introduction

The body of your message.

@component('mail::button', ['url' => ''])
Button Text
@endcomponent

Thanks,<br>
{{ config('app.name') }}
@endcomponent

resources/views/footer-public.blade.php
<footer class="ty-footer-public">
    <div class="container">
        <div class="ty-footer-public-content">
            <p>&copy; {{ __('THiNK FeST is een onderdeel van De Haagse Hogeschool') }} {{ now()->year }}. {{ __('Alle rechten voorbehouden.') }}</p>
            @auth
            <ul>
                <li><a href="{{ route('public.contact', app()->getLocale()) }}">Contact</a></li>
            </ul>
            @endauth
        </div>
    </div>
</footer>

resources/views/footer.blade.php
<div class="container">
    <img class="ty-footer-logo" src="{{ url('images/logo_hh.svg') }}">
</div>
<footer class="ty-footer">
    <div class="container">
        <!-- @if(Auth::user()->role_id == 30)
            <p>Editie: <a class="ty-nav-link @if(request()->routeIs('pages.edition.list')) active @endif" aria-current="page" href="{{ route('pages.edition.list') }}">{{ substr(\App\Models\Edition::where(['is_active' => 1])->first()->name, -4) }}</a></p>
        @else
            <p>Editie: {{ substr(\App\Models\Edition::where(['is_active' => 1])->first()->name, -4) }}</p>
        @endif -->
    </div>
</footer>

resources/views/navigation-menu-public.blade.php
<nav class="ty-nav">
    <div class="container">
        @guest
        <img class="ty-guest-logo" src="{{ url('images/logo_public.svg') }}">
        @endguest
        @auth
        <div class="navbar navbar-light navbar-expand-lg bg-transparent">
            <div class="ty-nav-container bg-white rounded">
                <a href="{{ route('public.dashboard', app()->getLocale()) }}"><img src="{{ url('images/logo.svg') }}"></a>
                @auth
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarItems" aria-controls="navbarItems" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarItems">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="ty-nav-link nav-link @if(request()->routeIs('public.dashboard')) active @endif" aria-current="page" href="{{ route('public.dashboard', app()->getLocale()) }}">{{ __('Home') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="ty-nav-link nav-link @if(request()->routeIs('public.dashboard')) active @endif" aria-current="page" href="{{ route('public.dashboard', app()->getLocale()) }}#programme">{{ __('Programma') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="ty-nav-link nav-link @if(request()->routeIs('public.press-kit')) active @endif" aria-current="page" href="{{ route('public.press-kit', app()->getLocale()) }}">{{ __('Toolkit') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="ty-nav-link nav-link @if(request()->routeIs('public.about-think-fest')) active @endif" aria-current="page" href="{{ route('public.about-think-fest', app()->getLocale()) }}">{{ __('THiNK FeST: het verhaal') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="ty-nav-link nav-link @if(request()->routeIs('public.ednext')) active @endif" aria-current="page" href="{{ route('public.ednext', app()->getLocale()) }}">EdNext</a>
                        </li>
                        <li class="nav-item">
                            <a class="ty-nav-link nav-link @if(request()->routeIs('public.faq')) active @endif" aria-current="page" href="{{ route('public.faq', app()->getLocale()) }}">{{ __('FAQ') }}</a>
                        </li>
                    </ul>
                    <div class="ty-dropdown dropdown d-none d-lg-flex">
                        @switch(app()->getLocale())
                            @case('en')
                                <a class="ty-nav-link nav-link" href="{{ route('public.dashboard', 'nl') }}">Nederlands</a>
                                @break
                            @case('nl')
                                <a class="ty-nav-link nav-link" href="{{ route('public.dashboard', 'en') }}">English</a>
                                @break
                        @endswitch
                    </div>
                    <div class="d-flex ty-nav-profile-box">
                        <li class="nav-item dropdown">
                            <a class="ty-nav-profile d-flex align-items-center rounded border nav-link" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <p>{{ auth()->user()->name }}</p>
                            </a>
                            <ul class="dropdown-menu rounded" aria-labelledby="navbarScrollingDropdown">
                                @if (Auth::user()->role_id == 30)
                                    <li><a class="dropdown-item" href="{{ route('dashboard') }}">{{ __('Beheren') }}</a></li>
                                @else()
                                    @if('2021-10-23 00:00:00' >= \Carbon\Carbon::now())
                                        <li><a class="dropdown-item" href="{{ route('dashboard') }}">{{ __('Beheren') }}</a></li>
                                    @endif()
                                @endif()
                                
                                <form method="POST" action="{{ route('logout') }}">
                                    @csrf
                                    <li>
                                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); this.closest('form').submit();">{{ __('Uitloggen') }}</a>
                                    </li>
                                </form>
                            </ul>
                        </li>
                    </div>
                </div>
                @endauth
            </div>
        </div>
        @endauth
    </div>
</nav>

resources/views/navigation-menu.blade.php
<nav class="ty-nav ty-nav-admin">
    <div class="container">
        <div class="navbar navbar-light navbar-expand-xl bg-transparent">
            <div class="ty-nav-container bg-white rounded">
                <div class="ty-nav-left">
                    <a href="{{ route('public.dashboard', 'nl') }}"><img src="{{ url('images/logo.svg') }}"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarItems" aria-controls="navbarItems" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="navbarItems">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="ty-nav-link nav-link @if(request()->routeIs('pages.draft.list')) active @endif" aria-current="page" href="{{ route('pages.draft.list') }}">Concepts</a>
                        </li>

                        <li class="nav-item">
                            <a class="ty-nav-link nav-link @if(request()->routeIs('pages.activity.list')) active @endif" aria-current="page" href="{{ route('pages.activity.list') }}">All Activities</a>
                        </li>

                        <li class="nav-item">
                            <a class="ty-nav-link nav-link @if(request()->routeIs('pages.program.list')) active @endif" aria-current="page" href="{{ route('pages.program.list') }}">My Programme</a>
                        </li>

                        @can('viewAny', \App\Models\Edition::class)
                        <li class="nav-item">
                            <a class="ty-nav-link nav-link @if(request()->routeIs('pages.user.list')) active @endif" aria-current="page" href="{{ route('pages.user.list') }}">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="ty-nav-link nav-link @if(request()->routeIs('pages.faq.list')) active @endif" aria-current="page" href="{{ route('pages.faq.list') }}">FAQ</a>
                        </li>
                        <li class="nav-item">
                            <a class="ty-nav-link nav-link @if(request()->routeIs('pages.tag.list')) active @endif" aria-current="page" href="{{ route('pages.tag.list') }}">Tags</a>
                        </li>
                        <li class="nav-item">
                            <a class="ty-nav-link nav-link @if(request()->routeIs('pages.location.list')) active @endif" aria-current="page" href="{{ route('pages.location.list') }}">Locations</a>
                        </li>
                        <li class="nav-item">
                            <a class="ty-nav-link nav-link @if(request()->routeIs('pages.trash.list')) active @endif" aria-current="page" href="{{ route('pages.trash.list') }}">Recycle bin</a>
                        </li>
                        <li class="nav-item">
                            <a class="ty-nav-link nav-link @if(request()->routeIs('pages.content.list')) active @endif" aria-current="page" href="{{ route('pages.content.list') }}">Content</a>
                        </li>
                        <li class="nav-item">
                            <a class="ty-nav-link nav-link @if(request()->routeIs('auth.register.view')) active @endif" aria-current="page" href="{{ route('auth.register.view') }}">Make user</a>
                        </li>
                        @endcan()
                    </ul>
                    <div class="d-flex ty-nav-profile-box">
                        <li class="nav-item dropdown">
                            <a class="ty-nav-profile d-flex align-items-center rounded border nav-link" href="#" id="navbarScrollingDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                                <p>{{ auth()->user()->name }}</p>
                            </a>
                            <ul class="dropdown-menu rounded" aria-labelledby="navbarScrollingDropdown">
                                <li><a class="dropdown-item" href="{{ route('public.dashboard', app()->getLocale()) }}">{{ __('Deelnemen') }}</a></li>
                                <form method="POST" action="{{ route('logout') }}">
                                    @csrf
                                    <li>
                                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); this.closest('form').submit();">Uitloggen</a>
                                    </li>
                                </form>
                            </ul>
                        </li>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>